### ISSUE TITLE
Update build on npm

### ISSUE THREAD

**Issue by nitriques** [liqweed/grunt-svninfo#8]
Version 1.0.0 seems to be committed to  master, but not npm

![image](https://cloud.githubusercontent.com/assets/771169/17650749/5c26b028-6223-11e6-930f-452163df66e2.png)

I am updating my build file to grunt 1.0.0 but can't right now. Thanks!

**Comment by liqweed** [comment]
Try now.

**Comment by nitriques** [comment]
Thanks!
